theme = "plain"
icons = "awesome"

[[block]]
block = "custom"
command = "gmail"
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 15.0
alert = 10.0
show_percentage = false

[[block]]
block = "disk_space"
path = "/home"
alias = "h"
info_type = "available"
unit = "GB"
interval = 20
warning = 15.0
alert = 10.0
show_percentage = false

[[block]]
block = "disk_space"
path = "/media/data"
alias = "d"
info_type = "available"
unit = "GB"
interval = 20
warning = 200.0
alert = 100.0
show_percentage = false

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB"
format_swap = "{SUm}MB"
icons = true
clickable = true
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time} {power}"

[[block]]
block = "sound"
driver = "pulseaudio"
show_volume_when_muted = true

[[block]]
block = "backlight"
step_width = 5

[[block]]
block = "net"
device = "enp9s0"
graph_up = false
hide_inactive = true
hide_missing = true
interval = 2
ip = false
speed_down = false
speed_up = true
ssid = false

[[block]]
block = "net"
device = "wlp8s0"
graph_up = false
hide_inactive = true
hide_missing = true
interval = 2
ip = false
speed_down = false
speed_up = true
ssid = true

[[block]]
block = "time"
interval = 15
format = "%d.%m.%y %R"
on_click = "gsimplecal"

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
