[icons]
name = "awesome5"
[icons.overrides]
bat_charging = ""
bat_discharging = ""
bat_empty = ""
bat_full = ""
bat_half = ""
bat_quarter = ""
bat_three_quarters = ""
cpu = ""
disk_drive = ""
memory_mem = ""
net_up = "⇈"
net_down = "⇊"
time = "⏳"
volume_muted = ""

[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = ""

[[block]]
block = "custom"
command = "gmail"
interval = 60
hide_when_empty = true

[[block]]
block = "disk_space"
alert = 10.0
alert_absolute = false
format = "{icon} {path^1}{available;G}"
info_type = "available"
interval = 300
path = "/"
unit = "GB"
warning = 15.0

[[block]]
block = "cpu"
format = "{barchart} {utilization} {frequency}"
interval = 10

[[block]]
block = "memory"
clickable = true
critical_mem = 95
critical_swap = 95
display_type = "memory"
format_mem = "{mem_used;G}"
format_swap = "{swap_used_percents}"
icons = true
interval = 60
warning_mem = 80
warning_swap = 80

[[block]]
#device = "BAT1"
device = "DisplayDevice"
block = "battery"
driver = "upower"
format = "{percentage:0} {time:0}"
#interval = 60

[[block]]
block = "sound"
driver = "auto"
show_volume_when_muted = true

[[block]]
block = "backlight"
step_width = 5
invert_icons = true

[[block]]
block = "net"
device = "enp0"
format = "{speed_down;M}"
format_alt = "{speed_up;M}{speed_down;M}"
hide_inactive = true
hide_missing = true
interval = 5

[[block]]
block = "net"
device = "wlan0"
format = "{signal_strength}{speed_down;M}"
format_alt = "{ssid}{speed_up;M}{speed_down;M}"
hide_inactive = true
hide_missing = true
interval = 5

[[block]]
block = "keyboard_layout"
format = "{layout}"
driver = "kbddbus"

#[[block]]
#block = "bluetooth"
#mac = ""
#format = "B{percentage}"
#format_unavailable = "B[x]"
#hide_disconnected = false

[[block]]
block = "time"
format = "%d.%m %R"
interval = 45
on_click = "gsimplecal"
