#!/usr/bin/bash

declare -a list=(
  "com.amazon.appmanager"
  "com.android.bips"
  "com.android.chrome"
  "com.android.companiondevicemanager"
  "com.android.hotwordenrollment.okgoogle"
  "com.android.printspooler"
  "com.coloros.athena"
  "com.coloros.backuprestore"
  "com.coloros.childrenspace"
  "com.coloros.filemanager"
  "com.coloros.gallery3d"
  "com.coloros.gamespace"
  "com.coloros.healthcheck"
  "com.coloros.healthservice"
  "com.coloros.karaoke"
  "com.coloros.oppoguardelf"
  "com.coloros.oppomultiapp"
  "com.coloros.video"
  "com.coloros.weather.service"
  "com.coloros.weather2"
  "com.coloros.wifibackuprestore"
  "com.facebook.appmanager"
  "com.facebook.services"
  "com.facebook.system"
  "com.fido.asm"
  "com.fido.uafclient"
  "com.google.android.apps.googleassistant"
  "com.google.android.apps.photos"
  "com.google.android.apps.wellbeing"
  "com.google.android.apps.work.oobconfig"
  "com.google.android.feedback"
  "com.google.android.gm"
  "com.google.android.googlequicksearchbox"
  "com.google.android.inputmethod.latin"
  "com.google.android.marvin.talkback"
  "com.google.android.onetimeinitializer"
  "com.google.android.printservice.recommendation"
  "com.google.android.projection.gearhead"
  "com.google.android.youtube"
  "com.google.ar.core"
  "com.google.ar.lens"
  "com.google.mainline.telemetry"
  "com.heytap.appplatform"
  "com.heytap.cast"
  "com.heytap.datamigration"
  "com.heytap.mcs"
  "com.heytap.music"
  "com.heytap.openid"
  "com.nearme.romupdate"
  "com.nearme.statistics.rom"
  "com.netflix.mediaclient"
  "com.netflix.partner.activation"
  "com.oppo.bttestmode"
  "com.oppo.lfeh"
  "com.oppo.sos"
  "com.oppoex.afterservice"
  "com.realme.wellbeing"
  "com.rongcard.eidapi"
  "com.ses.entitlement.o2"
  "com.tencent.soter.soterserver"
  "com.wapi.wapicertmanage"
)

for app in "${list[@]}"
do
    echo "$app"
    adb shell pm disable-user --user 0 "$app"
    sleep 2
done
