#!/usr/bin/bash

declare -a list=(
  "com.amazon.amazonvideo.livingroom"
  "com.apple.atve.sony.appletv"
  "com.disney.disneyplus"
  "com.google.android.leanbacklauncher"
  "com.google.android.marvin.talkback"
  "com.google.android.music"
  "com.google.android.play.games"
  "com.google.android.tv.bugreportsender"
  "com.google.android.tvlauncher"
  "com.google.android.tvrecommendations"
  "com.google.android.videos"
  "com.netflix.ninja"
  "com.netflix.partner.ncm"
  "com.qterics.da.product"
  "com.sony.dtv.airplayapp"
  "com.sony.dtv.b2b.hotelmode"
  "com.sony.dtv.b2b.importexport"
  "com.sony.dtv.b2b.noderuntime.normal"
  "com.sony.dtv.b2b.noderuntime.privilege"
  "com.sony.dtv.b2b.prosettings"
  "com.sony.dtv.b2b.rs232csupport"
  "com.sony.dtv.b2b.softap"
  "com.sony.dtv.b2b.vendorprotocol"
  "com.sony.dtv.b2b.webappruntimedrm"
  "com.sony.dtv.demosupport"
  "com.sony.dtv.demosystemsupport"
  "com.sony.dtv.interactivetvutil"
  "com.sony.dtv.interactivetvutil.output"
  "com.sony.dtv.multiscreendemo"
  "com.sony.dtv.smarthelp"
  "com.sony.dtv.smarthomesettings"
  "com.sony.dtv.smartmediaapp"
  "com.sony.dtv.sonyselect"
  "tv.samba.ssm"
)

for app in "${list[@]}"
do
    echo "$app"
    adb shell pm uninstall -k --user 0 "$app"
    sleep 2
done
