(add-to-list 'load-path (expand-file-name "settings" user-emacs-directory))
(require 'my_scratch)
(require 'my_package)
(require 'my_python)
(require 'my_keybindings)
(require 'dark-mint-theme)
(load-theme 'dark-mint t)
