(add-to-list 'load-path (expand-file-name "settings" user-emacs-directory))
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
(load-theme 'gruvbox t)
(require 'scratch_my)
(require 'keybindings_my)
(require 'package_my)
(require 'hooks_my)
(setq custom-file "~/.emacs.d/custom.el")
(load custom-file)
